/**
 * Fixed, deterministic limitation statements for Compiler v0.1 understand output.
 * Not generated by AI — static product honesty copy.
 */
export const UNDERSTAND_LIMITATIONS: readonly string[] = [
  "Summary is assembled only from Query Engine results over an existing ProjectModel.",
  "No repository scan, compiler pass, or source parse runs during understand.",
  "No AI, LLM, or natural-language generation is used.",
  "Architecture confidence is capped below certainty by the inference engine.",
  "Absence of a signal means evidence was not found, not that the concept is impossible.",
  "Explain/Trace/Verify capabilities are not included in this vertical slice.",
] as const;

export function collectUnknowns(options: {
  architectureUnknowns: readonly string[];
  domainCount: number;
  entrypointCount: number;
  architectureCount: number;
  dependencyCount: number;
  relationshipCount: number;
}): string[] {
  const unknowns: string[] = [];
  for (const item of options.architectureUnknowns) {
    if (!unknowns.includes(item)) {
      unknowns.push(item);
    }
  }
  if (options.domainCount === 0) {
    unknowns.push("No domains were reported by the Query Engine.");
  }
  if (options.entrypointCount === 0) {
    unknowns.push("No entry points were reported by the Query Engine.");
  }
  if (options.architectureCount === 0) {
    unknowns.push("No architecture patterns were reported by the Query Engine.");
  }
  if (options.dependencyCount === 0) {
    unknowns.push("No dependencies were reported by the Query Engine.");
  }
  if (options.relationshipCount === 0) {
    unknowns.push("No relationships were reported by the Query Engine.");
  }
  return unknowns.sort((a, b) => a.localeCompare(b));
}

export function formatConfidence(value: number): string {
  return value.toFixed(2);
}
